---
- name: Install programming tools
  community.general.pacman:
    name:
      - gdm
      - gnome-backgrounds
      - gnome-color-manager
      - gnome-console
      - gnome-control-center
      - gnome-disk-utility
      - gnome-keyring
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-extensions
      - gnome-tweaks
      - gvfs
      - gvfs-afc
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - loupe
      - nautilus
      - snapshot
      - sushi
      - tracker3-miners
      - xdg-desktop-portal-gnome
      - xdg-user-dirs-gtk
    state: present
  become: true
