---
- name: Install zsh
  kewlfft.aur.aur:
    use: paru
    name:
      - zsh
      - oh-my-zsh-git
    state: present
  become: true
  become_user: aur_builder

- name: Set zsh config
  ansible.builtin.template:
    src: zshrc.j2
    dest: /home/{{ user.name }}/.zshrc
    backup: false
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  become: true
  become_user: "{{ user.name }}"
