---
- name: Set pacman.conf
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    backup: false
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Start paccache timer
  ansible.builtin.systemd:
    name: paccache.timer
    state: started
    enabled: true
  become: true
