---
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: "0644"
    validate: 'visudo -cf %s'

- name: Install paru
  kewlfft.aur.aur:
    name: paru
    state: present
  become: true
  become_user: aur_builder

- name: Set paru.conf
  ansible.builtin.template:
    src: paru.conf.j2
    dest: /etc/paru.conf
    backup: false
    owner: root
    group: root
    mode: "0644"
  become: true
