---
- name: Install pipewire
  community.general.pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - gst-plugin-pipewire
      - libpulse
      - wireplumber
    state: present
  become: true

- name: Enable pipewire-pulse
  ansible.builtin.systemd:
    name: pipewire-pulse.service
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ user.name }}"
