name: ansible-lint
on: push

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main